### ISSUE TITLE
error gbqOptions = gcp.bigquery.BigQueryOptions.getDefaultInstance

### ISSUE THREAD

**Issue by limpst** [mathworks-ref-arch/matlab-google-bigquery#1]
Hi, 

Please help. 

>> gbq = gcp.bigquery.BigQuery('credentials.json') ;

gcp.bigquery.BigQuery (line 73)
                    gbqOptions = gcp.bigquery.BigQueryOptions.getDefaultInstance;

Java exception occurred:
java.lang.IllegalArgumentException: A project ID is required for this service but could not be
determined from the builder or the environment.  Please set a project ID using the builder.

	at shaded.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)

	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:285)

	at com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:91)

	at com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:30)

	at com.google.cloud.bigquery.BigQueryOptions$Builder.build(BigQueryOptions.java:86)

	at com.google.cloud.bigquery.BigQueryOptions.getDefaultInstance(BigQueryOptions.java:159)

**Comment by pallavikar** [comment]
@limpst : We'll need more details to understand the root cause for the error you are facing.

1. What version of MATLAB are you using ?
2. Which OS (Linux, Windows etc) are you running MATLAB on ?
3. Do you have access to a valid GCP subscription and access to a Project ID ?
4. Is BigQuery API enabled on the Google developers console ?
5. Were the steps mentioned within [Documentation/Authentication](https://github.com/mathworks-ref-arch/matlab-google-bigquery/blob/master/Documentation/Authentication.md) followed to access GCP credentials?
6. Does the file `credentials.json` referenced as input argument exist ? If yes, is it located within `Software\MATLAB\config` ?
7. Can you send us the output of the following command? >> `which('credentials.json')`
8. Can you run the function `Software\MATLAB\startup.m` and send us the output on your command window ? This will help us in finding whether the library was correctly installed and if everything is on path.

We should be able to help diagnose the scenario once we have your response to the above queries.

**Comment by limpst** [comment]
Hi 
What version of MATLAB are you using ? MATLAB R2019b
Which OS (Linux, Windows etc) are you running MATLAB on ? Windows
Do you have access to a valid GCP subscription and access to a Project ID ? yep (owner + bigquery admin)
Is BigQuery API enabled on the Google developers console ? yep
Were the steps mentioned within Documentation/Authentication followed to access GCP credentials? yep 
Does the file credentials.json referenced as input argument exist ? (i've used the file downloaded from google system) If yes, is it located within Software\MATLAB\config ? yes
Can you send us the output of the following command? >> which('credentials.json')
>>  which('credentials.json')
F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\config\credentials.json

Can you run the function Software\MATLAB\startup.m and send us the output on your command window ? This will help us in finding whether the library was correctly installed and if everything is on path.

Adding MATLAB-GBQ-SDK Paths
---------------------------
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\app
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\app\functions
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\app\system
Skipping F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\lib
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\config
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\script
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\script\Examples
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\test
Adding F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\test\unit
Skipping F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\sys\modules
Skipping F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-google-bigquery\Software\MATLAB\public
Initializing all modules
google-gcp-common-sdk-0.1.0.jar library exists in path.

**Comment by limpst** [comment]
I got result with python. but there was problem with matlab with the same credentials.json 

from google.cloud import bigquery
from google.oauth2 import service_account
credentials = service_account.Credentials.from_service_account_file('credentials.json')
project_id = 'sixth-tribute-311316'
client = bigquery.Client(credentials= credentials, project=project_id)
query_job = client.query("""
    SELECT * FROM `sixth-tribute-311316.crypto_basis_db.output_data` LIMIT 1000 
""")
results = query_job.result()
client = bigquery.Client(credentials= credentials, project=project_id)
# TODO(developer): Set dataset_id to the ID of the dataset that contains
#                  the tables you are listing.
dataset_id = 'sixth-tribute-311316.crypto_basis_db'
tables = client.list_tables(dataset_id)  # Make an API request.
print("Tables contained in '{}':".format(dataset_id))
for table in tables:
    print("{}.{}.{}".format(table.project, table.dataset_id, table.table_id))
Tables contained in 'sixth-tribute-311316.crypto_basis_db':
sixth-tribute-311316.crypto_basis_db.output_data
sixth-tribute-311316.crypto_basis_db.tmp_csv_crypto

**Comment by limpst** [comment]
javaaddpath 'F:\Project\서울숲\Y_매트랩 코드 공유\HwayoungLee\2. Kelly\mathworks-gcp-support\matlab-gcp-common\Software\MATLAB\lib\jar\google-gcp-common-sdk-0.1.0.jar' ; 
no problem with adding jar

**Comment by limpst** [comment]
plz let me know if you need more information to fix issue

**Comment by asollander** [comment]
Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Hwayoung Lee, PhD ***@***.***>
Skickat: Wednesday, April 21, 2021 7:48:57 PM
Till: mathworks-ref-arch/matlab-google-bigquery ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: Re: [mathworks-ref-arch/matlab-google-bigquery] error gbqOptions = gcp.bigquery.BigQueryOptions.getDefaultInstance (#1)


plz let me know if you need more information to fix issue

**Comment by pallavikar** [comment]
As your code is breaking at line 73, there is a `credentialsFilePath` picked up by MATLAB and we can try and verify if that's correct.

There are 2 ways this value is picked up:

1. which(`'credentials.json'`)
2. getenv(`'GOOGLE_APPLICATION_CREDENTIALS'`)

Can you try adding breakpoints as shown below to check the value of `credentialsFilePath` and `credentialsJ` ?
![image](https://user-images.githubusercontent.com/12878372/115603292-f9dd3d80-a2ad-11eb-955d-0c7def6e4690.png)
![image](https://user-images.githubusercontent.com/12878372/115603475-301abd00-a2ae-11eb-8804-c5bd234c81b3.png)

The expected response is as follows:
![image](https://user-images.githubusercontent.com/12878372/115603716-7cfe9380-a2ae-11eb-89ba-400cabfcaf14.png)

`credentialsJ` should be readable for you to confirm if the `projectId` and other attributes of the credentials are being read correctly.

![image](https://user-images.githubusercontent.com/12878372/115603799-97387180-a2ae-11eb-882a-10c0ae5ccff9.png)
![image](https://user-images.githubusercontent.com/12878372/115603839-a3bcca00-a2ae-11eb-98c4-59f073a9ca13.png)

Common reasons for above failure for you to check:

1. The environment variable `GOOGLE_APPLICATION_CREDENTIALS` has not been set. 
![image](https://user-images.githubusercontent.com/12878372/115605321-61948800-a2b0-11eb-8a6e-fd21930a1ee4.png)
2. MATLAB does not have read permissions for `credentials.json`.
3. Parsing issues have been seen when `credentials.json` was open and edited in a different OS before. e.g. Opened and edited in Unix prior to usage in Windows.

**Comment by limpst** [comment]
![image](https://user-images.githubusercontent.com/4195559/115630570-35741800-a33f-11eb-8ffb-ad65478e3290.png)

**Comment by limpst** [comment]
![image](https://user-images.githubusercontent.com/4195559/115630830-aa475200-a33f-11eb-9021-012b8091b48d.png)

**Comment by limpst** [comment]
![image](https://user-images.githubusercontent.com/4195559/115631106-2b064e00-a340-11eb-8230-58b35ce71487.png)

![image](https://user-images.githubusercontent.com/4195559/115631185-4c673a00-a340-11eb-9b1d-cadd13773dcf.png)
![image](https://user-images.githubusercontent.com/4195559/115631227-5be68300-a340-11eb-8f60-46c31b6dcc7a.png)

**Comment by limpst** [comment]
ServiceAccountCredentials{clientId=..., clientEmail=..., privateKeyId=..., transportFactoryClassName=com.google.auth.oauth2.OAuth2Utils$DefaultHttpTransportFactory, tokenServerUri=https://oauth2.googleapis.com/token, scopes=[], serviceAccountUser=null}

**Comment by limpst** [comment]
I don't see project id here
other info. inputted correctly, so I think credentials.json has read successfully.

**Comment by pallavikar** [comment]
I understand where you are encountering the error i.e. `gbqOptionsJ = BigQueryOptions.getDefaultInstance();`

I am however unable to reproduce the error on our end. 

Can you state the Java version in use?

Did the environment variable `GOOGLE_APPLICATION_CREDENTIALS` exist before or was it just created? 
If it was just created  you will need to restart MATLAB. If not please ignore this.

**Comment by limpst** [comment]
![image](https://user-images.githubusercontent.com/4195559/115632439-acf77680-a342-11eb-975d-23c0b49174c1.png)

**Comment by limpst** [comment]
I had the same error in another pc with higher java version 1.11

**Comment by limpst** [comment]
seem problem solved after MATLAB rerun. 
![image](https://user-images.githubusercontent.com/4195559/115632720-4d4d9b00-a343-11eb-8b09-47581486864e.png)

**Comment by pallavikar** [comment]
I think the environment variable GOOGLE_APPLICATION_CREDENTIALS was recently created and a running instance of MATLAB cannot read it unless you restart it so that system variables can be read.

Can you confirm if this solved your issue?

**Comment by limpst** [comment]
yep. Thanks a lot for your help.

**Comment by limpst** [comment]
Hi, would it be possible I install package once  and do not need to install package again? because whenever my matlab re-run , it show Undefined variable "gcp" or class "gcp.bigquery.BigQuery". so I have to run startup.m again.
